// examples/vue/src/App.vue
<script setup lang="ts">
import {
  Database,
  HealthiconsProvider,
  BloodBag,
  OxygenTank,
  ChartPie,
  BloodBagFilled24px
} from 'healthicons-vue';
</script>

<template>
  <Database />
  <OxygenTank color="red" height="36" width="36" />
  <BloodBag />
  <BloodBagFilled24px />

  <HealthiconsProvider
    :icon-props="{
      'color': '#1E441E',
      'stroke-width': 1,
      'width': '2em',
      'height': '2em',
    }"
  >
    <SomeOtherContainer>
      <ChartPie />
    </SomeOtherContainer>
  </HealthiconsProvider>
</template>

// examples/solid/src/App.tsx
import {
  BloodBag,
  BloodBagOutline24px,
  HealthIconsProvider,
} from 'healthicons-solid-js';

export default function App() {
  return (
    <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
      <BloodBag width={36} height={36} color="#1E441E" />
      <HealthIconsProvider
        iconProps={{
          color: '#1E441E',
          width: '2em',
          height: '2em',
        }}
      >
        <BloodBagOutline24px />
      </HealthIconsProvider>
    </div>
  );
}
